### PR TITLE
Adapt to Ibexa v4

### PR DESCRIPTION
**Pull request by emodric**
Hi @lolautruche , long time no see :)

This adapts `EzCoreExtraBundle` to Ibexa v4. Bascially renames everything `ez` to `ibexa`. The name of the bundle, bundle namespaces and Composer package have been kept for simplicity sake.

If you don't have time or will to work with this any more, I'm more than happy to take over the role of maintainer :)

Also adds the config for GH Actions, although they probably won't run until this is merged.

### CODE REVIEW

**Comment by lolautruche** [comment]
Hi @emodric 

Thank you for your PR!
I think we should first release v2.3 and branch it out, and then plan a v3 with all these changes.

I'd happily add you as maintainer 🙂

**Comment by emodric** [comment]
v3 is already released, it's for eZ Platform 3.x, so this should be v4.

You can create 3.x branch from current master, as the last commit there is actually 3.0.0, and then merge this.

**Comment by lolautruche** [comment]
Done ✔

**Comment by emodric** [comment]
Thanks @lolautruche :tada:

**Comment by lolautruche** [comment]
😉 
I just added you as maintainer in Packagist 🙂

**Comment by emodric** [comment]
Thanks <3

**Pull request merged**
