### PR TITLE
eZ Platform 3 support

### PR DESCRIPTION
**Pull request by emodric**
eZ migrated to Symfony 5 and Twig 3 today.

### CODE REVIEW

**Comment by lolautruche** [comment]
Thanks @emodric !
Could you please also update `.travis.yml` and the README?
Also, it seems that `composer.json` needs an update regarding security. I'd really appreciate if you could update as well ^^

**Comment by emodric** [comment]
Updated README and Travis. Not sure about what you mean about security & `composer.json` ?

**Comment by lolautruche** [comment]
@emodric see https://github.com/lolautruche/EzCoreExtraBundle/network/alerts

**Comment by emodric** [comment]
@lolautruche It seems that `RepositoryAuthenticationProvider` is not compatible with eZ Platform 3, but since eZ Platform 3 introduced the possiblity to login with email as well as username (https://github.com/ezsystems/ezpublish-kernel/pull/2944), maybe we can just disable it on v3?

**Comment by emodric** [comment]
> See https://github.com/lolautruche/EzCoreExtraBundle/network/alerts

@lolautruche Can't see those, those are only for repo owners ;)

**Comment by lolautruche** [comment]
> @lolautruche It seems that `RepositoryAuthenticationProvider` is not compatible with eZ Platform 3, but since eZ Platform 3 introduced the possiblity to login with email as well as username ([ezsystems/ezpublish-kernel#2944](https://github.com/ezsystems/ezpublish-kernel/pull/2944)), maybe we can just disable it on v3?

Or maybe we should start a new major version...

**Comment by emodric** [comment]
> Or maybe we should start a new major version...

We can do that, yes, even better!

**Comment by emodric** [comment]
@lolautruche This is now more or less ready for review. I've removed support for email authentication and view parameters injection since it is implemeneted in eZ kernel now.

Email authentication is not compatible with eZ kernel 8 anyhow, but if you don't want to remove view parameters injection, I can revert it?

**Comment by emodric** [comment]
So, it seems `ezpublish-kernel` is now `ezplatform-kernel`: https://github.com/ezsystems/ezplatform/pull/510

~~Will update it here as soon as their PR is merged.~~

On the other hand, it might be okay to merge this without the change to at least have a tagged beta version with the old `ezpublish-kernel` name

**Review by lolautruche — CHANGES_REQUESTED** [review]
I'd rather keep parameters injection, but deprecate them.
Please check the docs in `Resources/doc/` as well 😉 .
We also need an `UPGRADE-3.0.md` file, listing what was removed and what is deprecated (also the bumped dependencies maybe?).

**Comment by emodric** [comment]
@lolautruche I've reverted the removal of view parameters and removed obsolete docs.

There's already `UPGRADE-3.0.md` file in the root dir, however I don't know how relevant it is and what was the purpose of it originally.

**Comment by lolautruche** [comment]
Thanks @emodric .
`UPGRADE-3.0.md` is stille relevant. It comes from https://github.com/lolautruche/EzCoreExtraBundle/commit/8f172ac4273ffd74dd869bfe56fda64739ba32d6#diff-0901ceb76939b17cd920bc69aa52d21f , so I guess we're still at least one PR away from v3 after this one 😉

**Comment by emodric** [comment]
@lolautruche I've pushed an update to `UPGRADE-3.0.md`. WDYT?

**Review by lolautruche — APPROVED** [review]

**Pull request merged**
